"""add_deleted_at_to_posts

Revision ID: 10ff39eaa6d6
Revises: f28765d7effb
Create Date: 2026-01-15 02:37:36.655596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ff39eaa6d6'
down_revision: Union[str, None] = 'f28765d7effb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.drop_column('posts', 'deleted_at')
    # ### end Alembic commands ###
