"""ULID

Revision ID: aae6bb7f6407
Revises: a02c1c0612e9
Create Date: 2025-11-03 18:28:21.598542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae6bb7f6407'
down_revision: Union[str, None] = 'a02c1c0612e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.String(length=26),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
