"""drop_unused_indexes

Revision ID: cc7e3a21cf27
Revises: daf383bdaeef
Create Date: 2026-02-03 01:54:19.647357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7e3a21cf27'
down_revision: Union[str, None] = 'daf383bdaeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_posts_created_at")
    op.execute("DROP INDEX IF EXISTS ix_posts_status_created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###
